FROM maven:3-openjdk-17 AS builder

COPY ./src src/
COPY ./pom.xml pom.xml

RUN mvn clean package -DskipTests

FROM openjdk:17.0.1-jdk-slim
COPY --from=builder target/*.jar scheduler.jar
EXPOSE 8080
CMD ["java","-jar","scheduler.jar"]